[2021-07-19 20:32:33,424] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task3 2020-01-01T00:00:00+00:00 [queued]>
[2021-07-19 20:32:34,395] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task3 2020-01-01T00:00:00+00:00 [queued]>
[2021-07-19 20:32:34,397] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-19 20:32:34,397] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-07-19 20:32:34,398] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-19 20:32:34,848] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task3> on 2020-01-01T00:00:00+00:00
[2021-07-19 20:32:35,020] {standard_task_runner.py:52} INFO - Started process 6945 to run task
[2021-07-19 20:32:35,306] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task3', '2020-01-01T00:00:00+00:00', '--job-id', '62', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmps2s0yprp', '--error-file', '/tmp/tmpomrjibli']
[2021-07-19 20:32:35,460] {standard_task_runner.py:77} INFO - Job 62: Subtask task3
[2021-07-19 20:32:37,876] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task3 2020-01-01T00:00:00+00:00 [running]> on host airflowvm
[2021-07-19 20:32:39,999] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task3
AIRFLOW_CTX_EXECUTION_DATE=2020-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-01T00:00:00+00:00
[2021-07-19 20:32:40,000] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-07-19 20:32:40,001] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-07-19 20:32:40,366] {subprocess.py:75} INFO - Output:
[2021-07-19 20:32:43,549] {subprocess.py:83} INFO - Command exited with return code 0
[2021-07-19 20:32:44,847] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task3, execution_date=20200101T000000, start_date=20210719T203233, end_date=20210719T203244
[2021-07-19 20:32:48,062] {local_task_job.py:196} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-07-19 20:32:48,360] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 6945
[2021-07-19 20:32:48,984] {taskinstance.py:1264} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-07-19 20:32:48,984] {subprocess.py:89} INFO - Sending SIGTERM signal to process group
[2021-07-19 20:32:49,059] {process_utils.py:66} INFO - Process psutil.Process(pid=6945, status='terminated', exitcode=1, started='20:32:34') (6945) terminated with exit code 1
