[2021-07-19 20:33:41,369] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task4 2020-01-14T00:00:00+00:00 [queued]>
[2021-07-19 20:33:41,582] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task4 2020-01-14T00:00:00+00:00 [queued]>
[2021-07-19 20:33:41,583] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-19 20:33:41,583] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-07-19 20:33:41,587] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-19 20:33:41,716] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task4> on 2020-01-14T00:00:00+00:00
[2021-07-19 20:33:41,778] {standard_task_runner.py:52} INFO - Started process 8766 to run task
[2021-07-19 20:33:41,845] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task4', '2020-01-14T00:00:00+00:00', '--job-id', '117', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpvp6fkcol', '--error-file', '/tmp/tmp7m24jn9l']
[2021-07-19 20:33:41,866] {standard_task_runner.py:77} INFO - Job 117: Subtask task4
[2021-07-19 20:33:42,401] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task4 2020-01-14T00:00:00+00:00 [running]> on host airflowvm
[2021-07-19 20:33:43,290] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task4
AIRFLOW_CTX_EXECUTION_DATE=2020-01-14T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-14T00:00:00+00:00
[2021-07-19 20:33:43,291] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-07-19 20:33:43,315] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-07-19 20:33:43,470] {subprocess.py:75} INFO - Output:
[2021-07-19 20:33:46,547] {subprocess.py:83} INFO - Command exited with return code 0
[2021-07-19 20:33:46,903] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task4, execution_date=20200114T000000, start_date=20210719T203341, end_date=20210719T203346
[2021-07-19 20:33:47,370] {local_task_job.py:196} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-07-19 20:33:47,657] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 8766
[2021-07-19 20:33:49,139] {taskinstance.py:1264} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-07-19 20:33:49,140] {subprocess.py:89} INFO - Sending SIGTERM signal to process group
[2021-07-19 20:33:49,237] {process_utils.py:66} INFO - Process psutil.Process(pid=8766, status='terminated', exitcode=1, started='20:33:41') (8766) terminated with exit code 1
