[2021-07-19 20:32:33,871] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task1 2020-01-08T00:00:00+00:00 [queued]>
[2021-07-19 20:32:34,590] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task1 2020-01-08T00:00:00+00:00 [queued]>
[2021-07-19 20:32:34,590] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-19 20:32:34,611] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-07-19 20:32:34,611] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-19 20:32:35,239] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task1> on 2020-01-08T00:00:00+00:00
[2021-07-19 20:32:35,348] {standard_task_runner.py:52} INFO - Started process 6951 to run task
[2021-07-19 20:32:35,656] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task1', '2020-01-08T00:00:00+00:00', '--job-id', '63', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpy0_nazuo', '--error-file', '/tmp/tmp7lft1x8w']
[2021-07-19 20:32:35,737] {standard_task_runner.py:77} INFO - Job 63: Subtask task1
[2021-07-19 20:32:38,175] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task1 2020-01-08T00:00:00+00:00 [running]> on host airflowvm
[2021-07-19 20:32:40,361] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2020-01-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-08T00:00:00+00:00
[2021-07-19 20:32:40,362] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-07-19 20:32:40,410] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-07-19 20:32:40,786] {subprocess.py:75} INFO - Output:
[2021-07-19 20:32:43,835] {subprocess.py:83} INFO - Command exited with return code 0
[2021-07-19 20:32:44,923] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task1, execution_date=20200108T000000, start_date=20210719T203233, end_date=20210719T203244
[2021-07-19 20:32:48,131] {local_task_job.py:196} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-07-19 20:32:48,382] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 6951
[2021-07-19 20:32:48,985] {taskinstance.py:1264} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-07-19 20:32:48,985] {subprocess.py:89} INFO - Sending SIGTERM signal to process group
[2021-07-19 20:32:49,040] {process_utils.py:66} INFO - Process psutil.Process(pid=6951, status='terminated', exitcode=1, started='20:32:34') (6951) terminated with exit code 1
